---

# tasks file for docker
- name: Garantir instalacao do docker
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Instalando o docker
  apt:
    name: docker-ce
    update_cache: yes
    state: present
